version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm -g install typescript@4.5.3
      - npm install -g aws-cdk@2.1.0
  build:
    commands:
      - cd source/cdk
      - npm install
      - cd ..
      - cd custom-resource
      - npm install
      - cd ../job-submit
      - npm install
      - cd ../../deployment
      - chmod +x ./run-unit-tests.sh
      - ./run-unit-tests.sh
      - cd ../source/cdk
      - cdk deploy "streaming-mutable-*" --require-approval never
